### PR TITLE
GA-06

### LINKED ISSUE #10: GA-06: Implement KNN Algorithm for Diabetes dataset
# Description

Implement the KNN model for Diabetes dataset using scikit-learn, train and test the model in the metrics of Accuracy, Precision and Recall.

# Acceptance Criteria

- **Necessary preprocessing:**
    - Split the data into 80% for training and 20% for testing, using the same random seed for this dataset.
    - Any other data manipulation needed to train the model.
- **Training and testing:**
    - Use the sckiti-learn implementation of the model and train it with the respective dataset.
    - Evaluate the model in Accuracy, Precision and Recall
    - Plot the confusion matrix to observe the Accuracy, and any other useful plot.

## Additional Notes

Manual implementation of the KNN model is not necessary

### PR DESCRIPTION
**Pull request by Chacalerks**
# Description
The KNN model was applied to the Pima Indians Diabetes dataset and for Heart Failure dataset with rigorous testing and optimizations, including outlier removal, column exclusion, and dataset standardization.

# Related issues

Task: https://github.com/TheCsarbeat/proyecto1-IA/issues/10
Task: https://github.com/TheCsarbeat/proyecto1-IA/issues/11

# Screenshots
- **Best result of KNN model in Diabetes dataset**
image

- **Best result of KNN model in Heart Failure dataset**
image

### CODE REVIEW

**Comment by TheCsarbeat** [comment]
There are conflicts. It looks like p1.ipynb was deleted on your branch but is still on develop

**Comment by Chacalerks** [comment]
Yes, that happened because I renamed the p1 file to KNN and I implemented my functionalities there.

But it shouldn't be a problem because the merge will integrate the two notebooks

**Comment by Chacalerks** [comment]
I've updated the branch with the implementation for the task: https://github.com/TheCsarbeat/proyecto1-IA/issues/11.

The strategy implemented was to create a brute force script and then sort the best results for the tests. This approach was also applied to the first diabetes dataset.

**Review by fernandamurillo04 — APPROVED** [review]
Looks good

**Comment by TheCsarbeat** [comment]
> But it shouldn't be a problem because the merge will integrate the two notebooks

Not as of right now, the conflicts are still unresolved and if you're not careful when solving them, you will end up deleting `p1.ipynb` altogether

**Pull request merged**
